scripts/mysql/rt_create.sql
scripts/sqlserver/rt_create.sql
sct-base/src/main/java/org/sdo/sct/domain/Limits.java
sct-base/src/main/java/org/sdo/sct/domain/OwnershipVoucherEntry.java

Reverts secure-device-onboard/supply-chain-tools#1

Revert "add uuid column to voucher table"

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

The version for supply-chain-tools components to 1.9-SNAPSHOT to prepare
development for next release.

Roll version to 1.9-SNAPSHOT

---

README.md

The link for the SQL scripts were outdated. Also fixed some typos and
document formatting issues.

Fix link for SQL scripts

---

Jenkinsfile.yml

Added stage Run Smoke tests in jenkinsfile to run smoke tests on every
commit with the latest binaries of other SDO components.
Signed-off-by: Mareddy, Deepthi <depthix.mareddy@intel.com>

Updated Jenkins file to run smoke tests.

---

demo/docker_manufacturer/README.md
demo/docker_reseller/README.md

Signed-off-by: Tom Barnes <thomas.j.barnes@intel.com>

Update demo readme files with -not for production- note

---

demo/docker_manufacturer/README.md
demo/docker_manufacturer/docker-compose.yml
demo/docker_manufacturer/manufacturer.env

Adding Ondie ECDSA specific properties to manufacturer.env.
Signed-off-by: Chandrakar, Prateek <prateek.chandrakar@intel.com>

Update docker implementation for Ondie ECDSA

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

SCT version roll to 1.9 release from 1.9-SNAPSHOT.

Roll version to 1.9

---

demo/docker_manufacturer/README.md
demo/docker_reseller/README.md

- Adding link for keystore setup guide.
Signed-off-by: Darshini Parikh <darshini.k.parikh@intel.com>

Docker Manufacturer README update

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Roll version for 1.10 development

---

build/Dockerfile
build/README.md
demo/docker_manufacturer/Dockerfile-mariadb
demo/docker_manufacturer/README.md
demo/docker_reseller/Dockerfile-mariadb
demo/docker_reseller/README.md

Migrate build and runtime containers to use Ubuntu 20.04.

Migrate to use Ubuntu 20.04

---

README.md
demo/docker_manufacturer/README.md
demo/docker_reseller/README.md

Update README for fixing formatting issues

---

manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

SCT version roll to 1.10 release from 1.10-SNAPSHOT.

Roll version to 1.10

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Roll version for 1.10.1 development.

Roll version for 1.10.1 development

---

README.md
build/Dockerfile
build/build.sh
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version roll-over to 1.10.1 Release.

Version roll-over to 1.10.1 Release

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Prepare for 1.10.2 development

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_manufacturer/manufacturer.env
demo/docker_reseller/README.md
demo/docker_reseller/docker-compose.yml
demo/docker_reseller/reseller.env
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Roll version for 1.10.2 release

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover for 1.10.3 Development.

Version rollover for 1.10.3 Development

---

manufacturer-toolkit/pom.xml
pom.xml

Updating dependencies to the latest available version.

Updating dependencies

---

NOTICE
manufacturer-toolkit/pom.xml
manufacturer-toolkit/src/test/java/org/sdo/sct/mt/ControllerExceptionHandlerTest.java
pom.xml

Upgrading to the latest spring-boot version.
spring-boot-starter:2.3.11.RELEASE => spring-boot-starter:2.5.4

Upgrading to the latest spring-boot version

---

pom.xml

Upgrading spring boot version.

Upgrading spring boot version

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Roll version to 1.10.3 RELEASE.

Roll version to 1.10.3 RELEASE

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.4-SNAPSHOT.

Version rollover to 1.10.4-SNAPSHOT

---

manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.4 Release.

Version rollover to 1.10.4 Release

---

manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Adding Log4j-api 2.16.0 dependency.

Adding Log4j-api 2.16.0 dependency

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.5-SNAPSHOT.

Version rollover to 1.10.5-SNAPSHOT

---

manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.5 Release.

Version rollover to 1.10.5 Release

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.6-SNAPSHOT.

Version rollover to 1.10.6-SNAPSHOT

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.6 Release.

Version rollover to 1.10.6 Release

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.7-SNAPSHOT.

Version rollover to 1.10.7-SNAPSHOT

---

README.md
manufacturer-toolkit/pom.xml
pom.xml

Upgrading dependencies to latest version.

Upgrading dependencies to latest version

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.7 Release.

Version rollover to 1.10.7 Release

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.8 SNAPSHOT.

Version rollover to 1.10.8 SNAPSHOT

---

build/README.md
demo/docker_manufacturer/README.md
demo/docker_reseller/README.md

Updating Docker version in README.

Updating Docker version in README

---

demo/docker_manufacturer/docker-compose.yml
demo/docker_reseller/docker-compose.yml
manufacturer-toolkit/pom.xml
manufacturer-webapp/pom.xml
pom.xml
reseller-toolkit/pom.xml
reseller-webapp/pom.xml
sct-base/pom.xml

Version rollover to 1.10.8 Release.

Version rollover to 1.10.8 Release
